### ISSUE TITLE
Publish package to public repository

### ISSUE THREAD

**Issue by Tolsi** [Hansanto/kault#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hello, it can be handy for other devs. Even jitpack.io [can't build it as is](https://jitpack.io/com/github/Hansanto/kault/1.3.0/build.log)

**Comment by Hansanto** [comment]
Hello!

The package is present in [maven central](https://central.sonatype.com/search?q=g:io.github.hansanto+kault&smo=true).

There is a link in the [Wiki page](https://github.com/Hansanto/kault/wiki/01-%E2%80%90-Setup) (but I don't know why, the version is unknown, I will check that). For the moment, you use it with:

```kt
implementation("io.github.hansanto:kault:1.3.0")
```

**Comment by Hansanto** [comment]
I fixed the badge (wiki updated). Don't hesitate to say if you have an issue retrieving the package in Maven Central.

I tried locally to retrieve my package through Maven Central and I didn't have difficulty

**Comment by Tolsi** [comment]
Oops, sorry, I didn't find it. Thank you!
